### ISSUE TITLE
Implement !detainhistory

### ISSUE THREAD

**Issue by jfox13-nd** [ginglis13/shortstop#29]
Create a way of logging and returning how many times a user has been detained
Usage: !detainhistory @user
>> user has been detained x times

**Comment by ginglis13** [comment]
I was thinking maybe if you just call `!detain` w/o args, it will show you how many times you've been detained. and then to see all, just `!detain list` or something

**Comment by jfox13-nd** [comment]
That is way cooler 🚀

**Comment by joegrip** [comment]
This is done
